from .paths import ASSETS_DIR, DESKTOP_MODEL, GENERATED_ASSETS_DIR, PROJECT_ROOT, SOURCE_ASSETS_DIR, UI_DIR

__all__ = [
    "ASSETS_DIR",
    "DESKTOP_MODEL",
    "GENERATED_ASSETS_DIR",
    "PROJECT_ROOT",
    "SOURCE_ASSETS_DIR",
    "UI_DIR",
]
